### ISSUE TITLE
retrying on custom exception

### ISSUE THREAD

**Issue by neerfri** [safwank/ElixirRetry#10]
Thanks for the work on this library, I love the API! The use of streams is extremely clever.
I was wondering how do you see using this library with exceptions that are not `RuntimeError`

For example I need to wrap an `Ecto` save with optimistic lock that may raise a `Ecto. StaleEntryError`. I could not find a simple way to achieve this with the current code.
I ended up doing something quite complex (code below).

I wrap every call to `Retry.retry` so the code inside will transform a `raise` of whitelisted exceptions (in the calling code) to a `{:error, {:wrapped_exception, e}}` return value, and then transform this value back to a raised exception if the last retry returned this tuple.

```elixir
defmodule MyApp.Utils.Retry do
  defmacro __using__(_opts) do
    quote do
      import unquote(__MODULE__)
      import Retry.DelayStreams
    end
  end

  defmacro retry(exceptions, opts, do: block) do
    quote do
      require Retry
      Retry.retry(unquote(opts)) do
        unquote(__MODULE__).wrap_exceptions(unquote(exceptions)) do
          unquote(block)
        end
      end
      |> unquote(__MODULE__).unwrap_exceptions()
    end
  end

  defmacro wrap_exceptions(exceptions, do: block) do
    quote do
      try do
        unquote(block)
      rescue
        e in unquote(exceptions) ->
          {:error, {:wrapped_exception, e}}
      end
    end
  end

  def unwrap_exceptions(result) do
    case result do
      {:error, {:wrapped_exception, e}} -> raise(e)
      _ -> result
    end
  end
end
```

Using this codes stays more or less similar to the original API with the addition of the `exceptions` parameter:
```elixir
retry [Ecto.StaleEntryError], with: exp_backoff() |> randomize() |> expiry(5_000)  do
  # Some code that may raise Ecto.StaleEntryError
end
```

Do you think there's a better way to achieve this?
Was there a reason to only rescue from `RuntimeError`?
Would you be interested in a pull request that makes this a feature of the lib? (maybe using `exceptions: [...]` instead of a separate parameter)

Thanks again!

**Comment by safwank** [comment]
Hi @neerfri. Sorry for the late reply, I've been very busy lately. I hope to attend to this sometime this weekend!

**Comment by neerfri** [comment]
@safwank Thanks!
As I mentioned I would happily make a pull request to add a feature to pass a list of whitelisted exceptions to retry on.

**Comment by safwank** [comment]
@neerfri I prefer this syntax as I find it readable and semantic

```elixir
retry [Ecto.StaleEntryError], with: exp_backoff() |> randomize() |> expiry(5_000)  do
  # Some code that may raise Ecto.StaleEntryError
end
```

Also, if you could make the list of errors optional to maintain backwards compatibility, that'd be awesome.
