### ISSUE TITLE
Is there a way to retry on any error?

### ISSUE THREAD

**Issue by kagux** [safwank/ElixirRetry#14]
Hey,

First of all, thanks for great library!
Today I faced a problem when I needed to retry on any error. It appears that I have to list all possibilities. Is that intentional or missing because no one needed this before?

**Comment by safwank** [comment]
You're correct, I personally haven't had a need for it. Retrying on any error sounds a bit dangerous to me. Mind telling me why you need to do that?

**Comment by safwank** [comment]
By the way, have you considered `retry_while`?
