### ISSUE TITLE
access to result/error in then/else blocks?

### ISSUE THREAD

**Issue by stephanos** [safwank/ElixirRetry#18]
Just yesterday we were replacing some manual retry handling with `retry` and while we loved the cleanliness of it, it would have been even easier if the `then` and `else` blocks would contain the result of the retry block. Like this:
```
retry with: lin_backoff(500, 1) |> take(5) do
  ...
then
  result -> ...
else
  error -> ...
end
```
I don't know much about Elixir macros, but is this possible?

What we have done in our case now was to assign the result to a variable, ie `response = retry with: ...` and then did _another_ match on the response to distinguish the success and error case. That would be unnecessary if we could access those in the then/else blocks.

**Comment by safwank** [comment]
@stephanos IIRC this has been requested before, and the answer was although it's doable, it's not straightforward. Elixir's `try-rescue` macro does something similar, so I can probably get some inspiration from it. I'll add it to the TODO list.

**Comment by quolpr** [comment]
Really will be great to have such feature

**Comment by safwank** [comment]
@stephanos @quolpr FYI this is now available in v0.10.

**Comment by stephanos** [comment]
that's fantastic, thank you!

**Comment by quolpr** [comment]
Great! Thank you!
