### ISSUE TITLE
Different Atoms for Retry

### ISSUE THREAD

**Issue by rawkode** [safwank/ElixirRetry#21]
Hi,

I'm working on some middleware system and I'd like to use this library for retries.

The middleware already has an API that expects `{:ok, _}`, `{:skip, _}`, or `{:error, _}`

I'd like to use retry, but configure it only to retry on `{:retry, _}`

Having looked at the code, I don't believe this is possible. Would you accept a PR that made this configurable?

**Comment by safwank** [comment]
@rawkode Sure. You can pass the list of atoms as an option.

**Comment by safwank** [comment]
This has been included in v0.9. Thanks for the PR @rawkode.
