### ISSUE TITLE
Elixir compiler warning in application code with Retry 0.9.0

### ISSUE THREAD

**Issue by samsondav** [safwank/ElixirRetry#24]
Retry 0.9.0 gives us a new compiler warning in our own application code - notably:

```
warning: this clause cannot match because a previous clause at line 50 always matches
  lib/eggl/tasks/notify_close_io_on_deal_change.ex:50
```

The code looks like this:

```
50  retry with: lin_backoff(@closeio_backoff, 2) |> Stream.take(2) do
51    notify_close_io_about_deal_change(deal, analytics_ids)
52  end
```

This is a problem for us since we don't allow any application-generated warnings through CI. So we are blocked from upgrading to 0.9.0

**Comment by safwank** [comment]
@samphilipd This should be fixed in v0.9.1. Let me know if the problem persists.
