### ISSUE TITLE
exception stacktrace in else block

### ISSUE THREAD

**Issue by lowang** [safwank/ElixirRetry#38]
Hi

I was wondering about proper stacktrace inside `else` block, 
calling `System.stacktrace()` is producing deprecation warning.
I'm using sentry.io for error reporting.
I can craft some PR but I would like to consult first what would you suggest?

**Comment by safwank** [comment]
Hi. Thanks for reporting this. Let me look into it and get back to you.

**Comment by hoyon** [comment]
Isn't this just a matter of replacing https://github.com/safwank/ElixirRetry/blob/master/lib/retry.ex#L227 with 
```elixir
reraise e, __STACKTRACE__
```

**Comment by safwank** [comment]
@hoyon Thanks for that.

@lowang I've just released https://github.com/safwank/ElixirRetry/releases/tag/v0.14.1 which replaces the deprecated function with `__STACKTRACE__`.
