### ISSUE TITLE
Create github actions to validate tests and coverage upon PRs

### ISSUE THREAD

**Issue by am-kantox** [safwank/ElixirRetry#43]
Github can run tests and check the coverage blocking/allowing PR to be merged. I think it should be added (it’s extremely simple, feel free to assign the task to me.)

**Comment by safwank** [comment]
After merging your change yesterday I realised the Travis build was no longer working, so I migrated it to GitHub Actions which you can see in action [here](https://github.com/safwank/ElixirRetry/actions).

**Comment by am-kantox** [comment]
❤
