### ISSUE TITLE
Getting the retry attempt number in the body of retry

### ISSUE THREAD

**Issue by rosacris** [safwank/ElixirRetry#9]
Hi,

  we are using ElixirRetry in our project and we were wondering if it is possible to retrieve the current retry attempt count in the body of the retry macro.
  We are interested in such feature because we would like to increase HTTPotion timeout value in successive retries.

Thanks

**Comment by safwank** [comment]
Off the top of my head, doing so would be a bit tricky. Out of curiosity, why do you need to increase the timeout?

**Comment by rosacris** [comment]
Hi,

during the initialization of our Elixir service, we need to consume from another backend service using HTTP. Certain requests are slow no matter on the load (> x3 the averge). For such cases, we would like to have a way to increase the timeout threshold in HTTPotion, otherwise they will never be able to succeed.

**Comment by safwank** [comment]
OK. 

At any rate, it's a cool feature to have. I don't know if I can commit to it in the near future, but I welcome a PR.
